#!/usr/bin/env python2
'''
SSL interceptor and logger.
See --help for usage.
'''

from twisted.internet import reactor, ssl
import sys
import os
import mitmproxy

# disable reporting of bogus "no-member" errors
# pylint: disable=E1101


class ProxyServer(mitmproxy.ProxyServer):
    '''
    ProxyServer with implemented connect procedure
    '''
    def connect_to_server(self):
        '''
        Connect over SSL-encrypted raw socket
        '''
        factory = mitmproxy.ProxyClientFactory(
            self.transmit, self.receive, self.log)
        reactor.connectSSL(
            self.host, self.port, factory, ssl.ClientContextFactory())

    def _terminate(self):
        print "requests left: %s" % self.requests_left
        if self.requests_left == 0:
            print "terminating..."
            mitmproxy.ProxyServer._terminate(self)


def main():
    '''
    Parse options, open log and start proxy server
    '''
    (opts, _) = mitmproxy.proxy_option_parser(443, 4443)

    if not os.path.exists(os.path.expanduser('~/.mitmkeys/server.key')) \
    or not os.path.exists(os.path.expanduser('~/.mitmkeys/server.crt')):
        print "Please do create server certificates (see readme)."
        sys.exit(1)

    # log = mitmproxy.Logger()
    # if opts.logfile is not None:
    #     log.open_log(opts.logfile)
    log_list = []
    if opts.requests > 1:
        for i in range(opts.requests):
            log = mitmproxy.Logger()
            if opts.logfile is not None:
                log.open_log("{0}.part{1}".format(opts.logfile, i))
            log_list.append(log)
    else:
        log = mitmproxy.Logger()
        if opts.logfile is not None:
            log.open_log(opts.logfile)
        log_list.append(log)


    sys.stderr.write(
        'Server running on localhost:%d...\n' % opts.localport)

    factory = mitmproxy.MultiLogProxyServerFactory(
        ProxyServer, opts.host, opts.port, log_list)
    reactor.listenSSL(
        opts.localport, factory, ssl.DefaultOpenSSLContextFactory(
            os.path.expanduser('~/.mitmkeys/server.key'),
            os.path.expanduser('~/.mitmkeys/server.crt')))

    # for log in log_list:
    #     print log
    #     factory = mitmproxy.ProxyServerFactory(
    #         ProxyServer, opts.host, opts.port, log, 1)
    #     reactor.listenSSL(
    #         opts.localport, factory, ssl.DefaultOpenSSLContextFactory(
    #             os.path.expanduser('~/.mitmkeys/server.key'),
    #             os.path.expanduser('~/.mitmkeys/server.crt')))

    reactor.run()
    ret_code = mitmproxy.exit_code.pop()
    if ret_code != 0:
        sys.exit(ret_code)

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(0)
